services:
  api-quiz-bank:
    environment:
      QUIZBANK_TELEGRAM_BOT_TOKEN_FILE: /run/secrets/api_quiz_bank_telegram_bot_token
      TELEGRAM_BOT_TOKEN_FILE: /run/secrets/api_quiz_bank_telegram_bot_token
    volumes:
      - /root/api-quiz-bank/telegram-bot-token:/run/secrets/api_quiz_bank_telegram_bot_token:ro
      - /var/lib/api-quiz-bank/app-var:/app/var
