"""Shared default content scope values."""

DEFAULT_LANGUAGE_CODE = "de"
DEFAULT_CONTENT_BANK_ID = "german-core"
DEFAULT_BANK_VERSION = "2026-06-12-baseline"
DEFAULT_BANK_VERSION_ID = "german-core:2026-06-12-baseline"
DEFAULT_ALLOWED_LANGUAGE_CODES_JSON = '["de"]'
DEFAULT_ALLOWED_CONTENT_BANK_IDS_JSON = '["german-core"]'
DEFAULT_ALLOWED_BANK_VERSION_IDS_JSON = "[]"
DEFAULT_ALLOWED_CONTENT_TYPES_JSON = "[]"
