"""Compatibility facade for MVP database helpers."""

from __future__ import annotations

from .database_connection import (
    DEFAULT_DB_PATH,
    ROOT,
    PostgreSQLConnection,
    PostgreSQLUnsupportedSQLError,
    configured_database_url,
    configured_db_path,
    connect,
    connect_postgresql,
    decode_json_field,
    ensure_postgresql_supported_sql,
    new_id,
    row_to_dict,
    today_usage_date,
    translate_sqlite_placeholders,
    utc_now,
)
from .database_runtime import (
    MIGRATIONS_DIRECTORY,
    POSTGRESQL_MIGRATIONS_DIRECTORY,
    RUNTIME_TABLES,
    VISUAL_RUNTIME_TABLES,
    database_is_ready,
    initialize_database,
    initialize_postgresql_database,
    postgresql_is_ready,
    postgresql_table_names,
    sqlite_table_names,
    visual_database_is_ready,
)
from .database_seed import (
    DEFAULT_VISUAL_SETTINGS,
    insert_visual_asset,
    read_jsonl,
    reset_demo_delivery_state,
    seed_admin_credential,
    seed_api_credential,
    seed_consumer,
    seed_control_fixture,
    seed_demo_state,
    seed_entitlement,
    upsert_consumer_visual_settings,
    upsert_quiz_item,
)
from .database_status import (
    ALLOWED_CONSUMER_TRANSITIONS,
    ALLOWED_TRANSITIONS,
    DELIVERABLE_STATUSES,
    transition_consumer_status,
    transition_item_status,
)


__all__ = [
    "ALLOWED_CONSUMER_TRANSITIONS",
    "ALLOWED_TRANSITIONS",
    "DEFAULT_DB_PATH",
    "DEFAULT_VISUAL_SETTINGS",
    "DELIVERABLE_STATUSES",
    "MIGRATIONS_DIRECTORY",
    "POSTGRESQL_MIGRATIONS_DIRECTORY",
    "PostgreSQLConnection",
    "PostgreSQLUnsupportedSQLError",
    "ROOT",
    "RUNTIME_TABLES",
    "VISUAL_RUNTIME_TABLES",
    "configured_database_url",
    "configured_db_path",
    "connect",
    "connect_postgresql",
    "database_is_ready",
    "decode_json_field",
    "ensure_postgresql_supported_sql",
    "initialize_database",
    "initialize_postgresql_database",
    "insert_visual_asset",
    "new_id",
    "postgresql_is_ready",
    "postgresql_table_names",
    "read_jsonl",
    "reset_demo_delivery_state",
    "row_to_dict",
    "seed_admin_credential",
    "seed_api_credential",
    "seed_consumer",
    "seed_control_fixture",
    "seed_demo_state",
    "seed_entitlement",
    "sqlite_table_names",
    "today_usage_date",
    "transition_consumer_status",
    "transition_item_status",
    "translate_sqlite_placeholders",
    "upsert_consumer_visual_settings",
    "upsert_quiz_item",
    "utc_now",
    "visual_database_is_ready",
]
