#!/usr/bin/env python3
"""Inspect QuizBank corpus and write governance inventory artifacts."""

from __future__ import annotations

import csv
from collections import Counter
from pathlib import Path

from quizbank_common import (
    EXPECTED_HEADER,
    PARSER_PROFILE_ID,
    build_arg_parser,
    inventory_summary,
    load_inventory,
    print_json,
)


def write_csv(path: Path, fieldnames: list[str], rows: list[dict[str, object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as file:
        writer = csv.DictWriter(file, fieldnames=fieldnames, lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def source_inventory_rows(inventory) -> list[dict[str, object]]:
    rows = []
    for source in inventory.source_files:
        rows.append(
            {
                "source_id": source.source_id,
                "path": f"QuizBank/{source.filename}",
                "filename": source.filename,
                "format": "CSV",
                "source_state": source.source_state,
                "parser_profile_id": "" if source.is_template else PARSER_PROFILE_ID,
                "row_count_detected": source.row_count,
                "size_bytes": source.size_bytes,
                "checksum_sha256": source.checksum_sha256,
                "header_hash_sha256": source.header_hash_sha256,
                "is_service_template": str(source.is_template).lower(),
                "registered_at": "2026-05-07",
                "registered_by": "tooling",
                "notes": "service template; excluded from active corpus" if source.is_template else "",
            }
        )
    return rows


def checksum_rows(inventory) -> list[dict[str, object]]:
    return [
        {
            "source_id": source.source_id,
            "path": f"QuizBank/{source.filename}",
            "checksum_algorithm": "sha256",
            "checksum": source.checksum_sha256,
            "size_bytes": source.size_bytes,
        }
        for source in inventory.source_files
    ]


def manifest_text(inventory) -> str:
    lines = [
        "# Generated by `python3 tools/quizbank_inventory.py --write-artifacts`.",
        "# Source CSV files are source assets; this manifest is import planning metadata.",
        "manifest_version: 1",
        "generated_at: 2026-05-07",
        "parser_profiles:",
        f"  default: {PARSER_PROFILE_ID}",
        "sources:",
    ]
    for source in inventory.active_sources:
        default_status = source_default_status(inventory.rows_by_file[source.filename])
        lines.extend(
            [
                f"  - source_id: {source.source_id}",
                f"    path: QuizBank/{source.filename}",
                f"    parser_profile_id: {PARSER_PROFILE_ID}",
                "    import_mode: dry_run",
                "    source_state: active",
                f"    default_status: {default_status}",
                f"    checksum_sha256: {source.checksum_sha256}",
                f"    row_count_detected: {source.row_count}",
            ]
        )
    return "\n".join(lines) + "\n"


def source_default_status(rows: list[dict[str, str]]) -> str:
    counts = Counter(row.get("status", "").strip() for row in rows)
    if len(counts) == 1:
        return next(iter(counts))
    return "mixed"


def parser_profiles_text() -> str:
    columns = "\n".join(f"      - {column}" for column in EXPECTED_HEADER)
    return f"""# Generated baseline parser profile for current QuizBank CSV corpus.
parser_profiles:
  - parser_profile_id: {PARSER_PROFILE_ID}
    name: Current QuizBank canonical CSV parser
    format: CSV
    encoding: utf-8-sig
    delimiter: ","
    quotechar: '"'
    header_required: true
    expected_columns:
{columns}
    canonical_mappings:
      cefr_level: sublevel
      item_status: status
      source_item_id: item_id
    strict_header: true
    default_item_status: draft
"""


def write_artifacts(inventory) -> None:
    inventory_rows = source_inventory_rows(inventory)
    write_csv(
        Path("data/manifests/file_inventory.csv"),
        [
            "source_id",
            "path",
            "filename",
            "format",
            "source_state",
            "parser_profile_id",
            "row_count_detected",
            "size_bytes",
            "checksum_sha256",
            "header_hash_sha256",
            "is_service_template",
            "registered_at",
            "registered_by",
            "notes",
        ],
        inventory_rows,
    )
    write_csv(
        Path("data/manifests/source_checksums.csv"),
        ["source_id", "path", "checksum_algorithm", "checksum", "size_bytes"],
        checksum_rows(inventory),
    )
    write_text(Path("data/manifests/import_manifest.yml"), manifest_text(inventory))
    write_text(Path("data/parser_profiles/parser_profiles.yml"), parser_profiles_text())


def main() -> int:
    parser = build_arg_parser("Inspect QuizBank corpus.")
    parser.add_argument(
        "--write-artifacts",
        action="store_true",
        help="Write file inventory, checksums, import manifest and parser profiles.",
    )
    args = parser.parse_args()

    inventory = load_inventory(args.quizbank_dir)
    summary = inventory_summary(inventory)

    if args.write_artifacts:
        write_artifacts(inventory)

    if args.format == "json":
        print_json(summary)
    else:
        print(f"active_bank_files={summary['active_bank_files']}")
        print(f"active_rows={summary['active_rows']}")
        print(f"top_level_csv={summary['top_level_csv_count']}")
        print(f"templates={len(summary['template_files'])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
