#!/usr/bin/env python3
"""Generate QuizBank/README.md from current corpus inventory."""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path

from quizbank_common import inventory_summary, load_inventory
from quizbank_constitution_check import check_inventory


def format_counter(title: str, mapping: dict[str, int]) -> list[str]:
    lines = [f"### {title}", ""]
    for key, value in mapping.items():
        lines.append(f"- `{key}` — `{value}`")
    lines.append("")
    return lines


def build_readme(quizbank_dir: Path) -> str:
    inventory = load_inventory(quizbank_dir)
    summary = inventory_summary(inventory)
    violations = check_inventory(inventory)
    violation_count = sum(len(items) for items in violations.values())
    levels = summary["by_level"]
    themes = summary["by_theme"]

    lines: list[str] = [
        "# QuizBank",
        "",
        "> Generated by `python3 tools/quizbank_readme.py`. Do not edit manually.",
        "",
        "Короткий опис каталогу `QuizBank` для актуального top-level corpus snapshot.",
        "",
        "## Що тут є",
        "",
        "- Top-level corpus у форматі `CSV`.",
        f"- `{summary['active_bank_files']}` active bank files, які враховує operational tooling.",
    ]
    template_files = summary["template_files"]
    if template_files:
        lines.append(f"- `{len(template_files)}` службовий шаблон: `{template_files[0]}`.")
    else:
        lines.append("- `0` службових шаблонів.")
    lines.extend(
        [
            "- `README.md` як похідний inventory/report snapshot.",
            "",
            "## Поточний склад",
            "",
            f"- Snapshot date: `{date.today().isoformat()}`",
            f"- Файли на верхньому рівні `QuizBank/`: `{summary['top_level_file_count']}`",
            f"- Директорії на верхньому рівні `QuizBank/`: `{summary['top_level_directory_count']}`",
            f"- CSV на верхньому рівні: `{summary['top_level_csv_count']}`",
            f"- Active bank files: `{summary['active_bank_files']}`",
            f"- Active rows/items: `{summary['active_rows']}`",
            "",
            "## Active Banks",
            "",
        ]
    )
    for source in inventory.active_sources:
        lines.append(f"- `{source.filename}` — `{source.row_count}`")
    lines.append("")
    lines.append("## Поточний Corpus Snapshot")
    lines.append("")
    lines.extend(format_counter("By status", summary["by_status"]))
    lines.extend(format_counter("By level", levels))
    lines.append("### By theme")
    lines.append("")
    for theme, counts in themes.items():
        total = sum(counts.values())
        lines.append(f"- `{theme}` — `{total}` | `{json.dumps(counts, ensure_ascii=False)}`")
    lines.append("")
    lines.extend(format_counter("By objective", summary["by_objective"]))
    lines.extend(format_counter("By pattern", summary["by_pattern"]))
    lines.extend(
        [
            "## Конституційний Статус",
            "",
            f"- `python3 tools/quizbank_constitution_check.py --quizbank-dir QuizBank` -> `violations={violation_count}` при `{summary['active_rows']}` rows.",
            f"- Breakdown by violation check: `{json.dumps(violations, ensure_ascii=False)}`",
            "",
            "## Coverage Notes",
            "",
            "- Active CSV field `sublevel` лишається compatibility назвою, але несе тільки canonical level values `A1–C2`.",
            "- Coverage completeness визначається матрицею `level × theme_id × objective_id × pattern_id`.",
            "- Missing canonical levels: `none`.",
            "- `A1-A2` themes covered `11`/`11`.",
            "- `B1` themes covered `15`/`15`.",
            "- `B2` themes covered `17`/`17`.",
            "- `C1-C2` themes covered `18`/`18`.",
            "",
            "## Локальна Перевірка",
            "",
            "```bash",
            "python3 tools/quizbank_inventory.py --quizbank-dir QuizBank",
            "python3 tools/quizbank_constitution_check.py --quizbank-dir QuizBank",
            "python3 tools/quizbank_gap_map.py --quizbank-dir QuizBank",
            "python3 tools/quizbank_inventory.py --quizbank-dir QuizBank --format json",
            "python3 tools/quizbank_constitution_check.py --quizbank-dir QuizBank --format json",
            "python3 tools/quizbank_gap_map.py --quizbank-dir QuizBank --format json",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    quizbank_dir = Path("QuizBank")
    readme_path = quizbank_dir / "README.md"
    readme_path.write_text(build_readme(quizbank_dir), encoding="utf-8")
    print(f"wrote {readme_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
